universe = container
container_image = docker://sabcook/fam-diffusion:v1

executable = gputest.sh

transfer_input_files = train.py, adm_unet.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_gpus = 1
+GPUJobLength = "short"

output = gputest.out
error  = gputest.err
log    = gputest.log

request_cpus   = 2
request_memory = 16GB
request_disk   = 8GB

queue