universe = container
container_image = docker://sabcook/fam-diffusion:v1

executable = gen100.sh

transfer_input_files = sample.py, adm_unet.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_gpus = 1
gpus_minimum_memory = 40000
gpus_minimum_capability = 8.0
gpus_maximum_capability = 9.0
+GPUJobLength = "short"

output = gen100.out
error  = gen100.err
log    = gen100.log

request_cpus   = 2
request_memory = 16GB
request_disk   = 8GB

queue