universe = container
container_image = docker://sabcook/fam-diffusion:v1

executable = memcheck.sh

transfer_input_files = memorization_check.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_gpus = 1
gpus_minimum_memory = 40000
gpus_minimum_capability = 8.0
gpus_maximum_capability = 9.0
+GPUJobLength = "short"

output = memcheck.out
error  = memcheck.err
log    = memcheck.log

request_cpus   = 2
request_memory = 24GB
request_disk   = 8GB

queue