universe = container
container_image = docker://sabcook/fam-diffusion:v1

executable = run100k.sh

transfer_input_files = train.py, adm_unet.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_gpus = 1
+GPUJobLength = "long"

output = run100k.out
error  = run100k.err
log    = run100k.log

request_cpus   = 2
request_memory = 24GB
request_disk   = 16GB

queue