universe = container
container_image = docker://sabcook/fam-diffusion:v1

executable = test1_run.sh

transfer_input_files = ../evaluation/fid_real_vs_real_prep.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_gpus = 1
gpus_minimum_memory = 10000
gpus_minimum_capability = 8.0
gpus_maximum_capability = 9.0
+GPUJobLength = "short"

output = test1.out
error  = test1.err
log    = test1.log

request_cpus   = 2
request_memory = 24GB
request_disk   = 12GB

queue